#SDRTrunk - SDR Trunking Decoder Application Settings
#Tue Apr 07 19:32:35 EDT 2026
audio.channel.panel.color.background=-16777216
audio.channel.panel.color.label=-4144960
audio.channel.panel.color.muted=-65536
audio.channel.panel.color.value=-16711936
root.directory=SDRTrunk
settings.currentFilename=settings.xml
settings.defaultFilename=settings.xml
spectral.display.dft.size=FFT04096
spectral.display.enabled=true
spectral.display.frame.rate=20
